version: "3.7"

networks:
  apinetwork:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET:-10.0.0.0/24}
          gateway: ${DOCKER_GATEWAY:-10.0.0.1}

services:
  api:
    image: golang:1.22-bullseye
    build: .
    environment:
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8080}
    volumes:
      - .:/app/go_service
      - go_environment:/go
    working_dir: /app/go_service
    tty: true
    command: go run main.go
    ports: 
      - ${API_PORT:-8080}:${API_PORT:-8080}
    networks:
      apinetwork:
        ipv4_address: ${API_HOST}

volumes:
  go_environment:
