version: "3.7"

services:
  sample_api:
    image: golang:1.22-bullseye
    build: .
    volumes:
      - .:/app/go_service
      - go_environment:/go
    working_dir: /app/go_service
    command: go run main.go
    ports: 
      - 8080:8080

volumes:
  go_environment:
