version: "3.7"

services:
  sample_api:
    image: golang:1.17.5-bullseye
    build: .
    volumes:
      - .:/app/go_service
      - go_environment:/go
    working_dir: /app/go_service
    command: bash -c "go mod download && go run ."
    ports: 
      - 8080:8080

volumes:
  go_environment:
    name: go_environment